<template>
	<div class="card mb-4 mt-8 text-left border-solid border border-slate-500">
		<h5 class="card-header text-xl ledaing-10 ">{{ json.name }} </h5>
		<div class="card-body p-4">
			<p class="my-4">Choose a command:</p>
			<select name="selectBox" class="form-select " size="4" aria-label="size 5 select example">
				<option class="w-full text-base" v-for="option in json.options" :key="option.key" :value="option.key">
					{{ option.name }}
				</option>
			</select>

			<div class="col-md-12 mb-2">
				<video id="vid_fbp" width="100%" preload="metadata" playsinline="" controls="">
					<source src="./../../static/videos/fruits_and_bottles.mp4" type="video/mp4">
				</video>
			</div>

			<div class="row" id="content_draw_1">
				<div class="col-md-12" id="code_draw_1">
					<p>Code generated by our Language Model Program (<a href="./../../static/codegen/draw/1.txt">raw text file</a>):
					</p>
				</div>
			</div>
			<div class="leading-6 mt-2 mb-6">
				<p>
					Prompts:
					<br>
					<a href="https://code-as-policies.github.io/prompts/draw_ui.txt">High-Level UI</a> |
					<a href="https://code-as-policies.github.io/prompts/parse_obj_name.txt">Parse Object Names</a> |
					<a href="https://code-as-policies.github.io/prompts/parse_shape_pts.txt">Parse Shape Points</a> |
					<a href="https://code-as-policies.github.io/prompts/transform_shape_pts.txt">Transform Shape
						Points</a> |
					<a href="https://code-as-policies.github.io/prompts/fgen_simple.txt">Function Generation</a>
				</p>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	props: { json: Object }
}

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.card {
	position: relative;
	display: flex;
	flex-direction: column;
	min-width: 0;
	word-wrap: break-word;
	background-color: #f8f9fa;
	background-clip: border-box;
	border: 1px solid rgba(0, 0, 0, .125);
	border-radius: .25rem;
}

.card-header {
	padding: .5rem 1rem;
	margin-bottom: 0;
	background-color: rgba(0, 0, 0, .03);
	border-bottom: 1px solid rgba(0, 0, 0, .125);
}

.card-body {
	flex: 1 1 auto;
	padding: 1rem 1rem;
}

.form-select {
	display: block;
	width: 100%;
	padding: .375rem 0 .375rem .75rem;
	-moz-padding-start: calc(0.75rem - 3px);
	font-size: 1rem;
	font-weight: 400;
	line-height: 1.5;
	color: #212529;
	background-color: #fff;
	background-image: "url(data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M2 5l6 6 6-6'/%3e%3c/svg%3e)";
	background-repeat: no-repeat;
	background-position: right .75rem center;
	background-size: 16px 12px;
	border: 1px solid #ced4da;
	border-radius: .25rem;
	transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
}

.form-select[multiple],
.form-select[size]:not([size="1"]) {
	/* padding-right: .75rem; */
	background-image: none;
}
</style>
